services:
  - type: web
    name: network-pharmacology-publication-api
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
